slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
spring:
  batch:
    job:
      enabled: true
      name: ${job.name:NONE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/crypto-automation'
    username: root
    password: 1emdgkqrur
  sql:
    init:
      mode: never